### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by McruvieWeb** [ManicRobot/rttsvg#1]
Hello,
Im new to python and have been trying to play around with your code to hopefully learn from it and use it for a DnD project down the line. However I cant get it to work!
Ive downloaded the code and have touched nothing to see how it runs on its own, but upon running I get the error:

" FileNotFoundError: [WinError 2] The system cannot find the file specified " along with some tracebacks. Any help with this would be amazing, and I can supply more information if you ask!

Also, I do have all the requirements installed :)

**Comment by nokyan** [comment]
Hey there, welcome to Python!
Could you maybe show the whole traceback? You can censor your name from the paths if you want, but I need the tracebacks to see what's gone wrong. :)

**Comment by McruvieWeb** [comment]
Thank you for the response, the full traceback is;

File "C:\Users\myname\Desktop\Bot\rttsvg.py", line 313, in <module>
    generate_video()
  File "C:\Users\myname\Desktop\Bot\rttsvg.py", line 166, in generate_video
    generate_TTS(reddit_post[0]["data"]["children"][0]["data"]["title"])
  File "C:\Users\myname\Desktop\Bot\rttsvg.py", line 91, in generate_TTS
    LENGTH += get_length(filename)
  File "C:\Users\Cammy\Desktop\Bot\rttsvg.py", line 99, in get_length
    result = subprocess.run(["ffprobe", "-v", "error", "-show_entries",
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by nokyan** [comment]
Oh, it looks like the script has trouble finding a program called ffprobe, it usually comes with ffmpeg.
Do you have ffmpeg installed? You can check by opening a command prompt, typing either "ffmpeg" or "ffprobe" and looking at the output: if it says something like "Command not found", it's not installed.
Installing ffmpeg on Windows is unfortunately not quite trivial, I found a (wikihow out of all sites) tutorial on that here: https://www.wikihow.com/Install-FFmpeg-on-Windows
Important is that the ffmpeg and ffprobe executables are somewhere in a folder in your Path environment variable, that way the command prompt and Python can find the executables, the wikihow tutorial seems to take care of that.
If it still doesn't work, tell me. :)

**Comment by McruvieWeb** [comment]
Perfect, thanks for that, Ill give it a shot and will let you know if it doesnt work!
Cheers!

**Comment by McruvieWeb** [comment]
Well this completely fixed the initial problem, it now goes all the way through the code start to end with no errors, however now when its done, the finished file doesnt exist... XD

It says that its located in C:\Users\myname\Desktop\Bot\nameofthegeneratedvideo which is where the rest of the program is contained, but when I open the folder nothing is there except the initial code

Apologies for being sucha pain, once I get it working how you designed it to, I can then start working backwards and impliment it into my dnd games I hope!

**Comment by nokyan** [comment]
That's weird. Can you try again and write what the name of the file should have been? My first suspicion is that the file name contains a character that Windows doesn't like, my script doesn't check for that because I'm using Linux and Linux has more relaxed rules when it comes to filenames.
Since the script by default pulls from r/AskReddit, titles typically have a : or a ? in them, which isn't allowed in Windows file names (https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names). Maybe I should implement a filter or something similar for that.
You could also change the subreddit in config.json for one where titles normally don't include special characters.

Oh, in the traceback you posted, you forgot to censor your name in the 4th C:\\... path :)

**Comment by Luphaestus** [comment]
@ManicRobot You are right. Renamed output name and it now works.

**Comment by nokyan** [comment]
@McruvieWeb Does that fix it for you too?

**Comment by McruvieWeb** [comment]
Only got round to trying it now, yeah that fixed it! Took a while to find a reddit with no special characters in the titles, but works perfectly now!

First project as a begginer of python - figure out where you coded the file name into it and try to change it (without breaking everything else!)
